aliyun:
  oss:
    endpoint: ${OSS_ENDPOINT:}
    public-endpoint: ${OSS_PUBLIC_ENDPOINT:}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    bucket-name: ${ALIYUN_OSS_BUCKET_NAME:}
    role-arn: ${ALIYUN_OSS_ROLE_ARN:}
#    image-process-embedding: ${APP_ALIYUN_OSS_IMAGE_PROCESS_EMBEDDING:${APP_CLOUD_OBJECT_STORAGE_IMAGE_PROCESS_EMBEDDING:image/resize,l_2048,m_lfit/format,jpg/quality,q_75}}
  ocr:
    access-key-id: ${ALIYUN_ACCESS_KEY_ID:}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET:}
    endpoint: ${OCR_ENDPOINT:}

app:
  vector:
    index-name: smart_gallery_cloud
    indexVersion: v2
    read-alias: smart_gallery_cloud_read
    write-alias: smart_gallery_cloud_write
    dimension: 1024
  kb-segment:
    index-name: kb_segment_cloud
    indexVersion: v1
    read-alias: kb_segment_cloud_read
    write-alias: kb_segment_cloud_write
    dimension: 1024
  embedding:
    image-input-mode: url
    model: multimodal-embedding-v1
    preprocess-version: v1
